import Head from 'next/head';
import {
  FaGithub,
  FaEnvelope,
  FaLinkedin,
  FaTwitter,
  FaFacebook,
  FaInstagram
} from 'react-icons/fa';
import Header from '../components/header';

export default function About() {
  return (
    <>
      <Head>
        <title>VARUNDEF | About Pham Trung Anh Vu</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='w-3/4 m-auto flex flex-col lg:mt-8'>
        <Header />
        <div className=''>
          <p className='mt-4'>
            I am Vu Pham, a skilled web developer based in Vietnam, specializing in .NET Core,
            Angular, and TypeScript. With a passion for clean code and cutting-edge technologies, I
            build scalable web applications and continuously expand my knowledge of cloud
            technologies like Azure and AWS.
          </p>
          <p className='text-xl w-max font-semibold mb-4 mt-8 bg-yellow-100'>Find me at</p>
          <div className='flex flex-wrap'>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaEnvelope className='mr-2' />
              <a href='mailto:anhvupt2412@gmail.com' className='underline'>
                anhvupt2412@gmail.com
              </a>
            </div>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaLinkedin className='mr-2' />
              <a
                href='https://www.linkedin.com/in/anhvupt'
                target='_blank'
                rel='noopener noreferrer'
                className='underline'>
                linkedin.com/in/anhvupt
              </a>
            </div>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaGithub className='mr-2' />
              <a
                href='https://github.com/anhvupt'
                target='_blank'
                rel='noopener noreferrer'
                className='underline'>
                anhvupt
              </a>
            </div>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaTwitter className='mr-2' />
              <a
                href='https://twitter.com/anhvupt'
                target='_blank'
                rel='noopener noreferrer'
                className='underline'>
                @anhvupt
              </a>
            </div>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaFacebook className='mr-2' />
              <a
                href='https://www.facebook.com/anhvupt98'
                target='_blank'
                rel='noopener noreferrer'
                className='underline'>
                fb.me/anhvupt98
              </a>
            </div>
            <div className='flex items-center mb-4 lg:w-1/2'>
              <FaInstagram className='mr-2' />
              <a
                href='https://www.instagram.com/_anhvupt'
                target='_blank'
                rel='noopener noreferrer'
                className='underline'>
                @_anhvupt
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
